# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RapidSsh < Formula
  desc ""
  homepage "https://github.com/achalpathak/rapid_ssh"
  version "0.3"

  on_macos do
    url "https://github.com/achalpathak/rapid_ssh/releases/download/v0.3/rapid_ssh_0.3_darwin_all.tar.gz"
    sha256 "7d30a5bf5d8a26b56385f22deb6a814f0d7bf8d2c6ac4b744f6d1e6353e10d55"

    def install
      bin.install "rapid_ssh"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/achalpathak/rapid_ssh/releases/download/v0.3/rapid_ssh_0.3_linux_amd64.tar.gz"
      sha256 "a2fe7e96cf8f3a0926f1b228df8d080be2f3ba95700a4a7cc2849622af45bfb3"

      def install
        bin.install "rssh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/achalpathak/rapid_ssh/releases/download/v0.3/rapid_ssh_0.3_linux_arm64.tar.gz"
      sha256 "512298a89ce8a85f4598069b159fb0204ad3d5bc46f680a71b5424d1a2ae942f"

      def install
        bin.install "rssh"
      end
    end
  end
end
